### ISSUE TITLE
Arvostelu ja kentät

### ISSUE THREAD

**Issue by dezhidki** [TIM-JYU/TIM#1418]
In GitLab by @vesal on Jun 20, 2019, 08:58

**Tehtävät:**
* [ ]  numericfiled ongelmat eri selainten ja , ja . kanssa
* [ ]  Erilaisten oikeuksien ja aikarajojen pika-asetus save-buttonnilla (ks #1446)
* [ ]  -pointsRule fieldeihin
* [ ]  csPluginissa on attribuutit: `validityCheck` ja `validityCheckMessage` tarkista että samat nimet
       textfield ja numericfield
* [ ]  Opettajan näkymän tekeminen hidasta (ks #1458)
* [ ]  Ongelmia isojen n. 300x20 taulukoiden kanssa
* [ ]  iPadilla ei tule varoitusta jos kenttiä muutettu ja poistutaan
* [ ]  multisavelle voi viedä parametrina kenttiä.  Sama pitäisi tehdä jsrunnerille, niin
       voi helposti vaihtaa laskennan kohdetta
* [ ]  Kaikkien attribuuttien antaminen defaultplugin rivillä
* [ ]  readonly antaminen myös yksittäiselle pluginille
* [ ]  Readonly kaikille käyttäjille (summa yms kannattaisi olla tällaisia)
* [x]  Jos taulukko oletuksena open: false, niin se lasketaan vasta avattaessa, sama raporteille
* [ ]  Laskentafunktioon optio, jolla voi pyytää samanlaisen refresh kuin käyttäjiä selatessa jotta näyttö uudistuu
* [x]  Ryhmän antaminen dokumentin asetuksissa
* [ ]  Taulukon rivi nro 2 suodatinriviksi... suodatinten tallennus puuttuu
* [ ]  demojen yms summat, ks. #1363
* [ ] import, ks #1421
* [ ] jos ei laskentaoikeutta ja painike näkyy, ryhmänä käytetään vaan kirjaantuneita (eli yleensä vain itseään)
      Taitaa toimia jo automaattisesti?
* [ ] taulukon ekaan sarakkeeseen mahdollisuus laittaa järjestysnumero joka on juokseva vaikka
      suodattaisi (eli numeroita on vähemmän silloin).  Numerot tulee, mutta eivät juoksevasti... `nrColumn: true`
* [x] raportti tuottaa liian ison URLin oikealla aineistolla. Raportti pitää tehdä palvelimen päässä
sille viedyistä parametreista ja se pitää voida bookmarkata.
* [ ]  raportille myös mahdollisuus html taulukkomuodoksi jos haluaa printata.  Käytetään jotakin lajittelevaa HTML-taulukkoa
* [ ] dropdown ei merkkiä ettei tallennettu
* [ ] drag myös fields joukkoon
* [ ] drag/drop komponentilla ei ole autosave
* [ ] lazy hirveän näköinen dropdown ja drag
* [ ] sivu jossa paljon kenttiä kammottavan näköinen jos anonyymi menee sinne
* [ ] dropdown (ja lie drag) eivät tottele `form-mode: true` vaan näyttävät browseria
* [ ] ainakin numericfield yrittää tallentaan kentän johon saavutaan tabilla, pitäisi tallentaa
      vain kenttä josta lähdetään
* [ ] jos ei ole automaattinen tilan vaihtaminen päällä opettajan näkymässä, on liikuminen jopa vaarallista, sillä
      kenttää jää edellisen käyttäjän tiedot ja kentän koskeminen aktivoi sen ja pois lähteminen
      aiheuttaa tallentamisen ja näin arvot tallentuvat väärin käyttäjän tietämättä
* [ ] readOnlyStyle voisi olla sellainen, että plaintext tekee kuten nyt ihan tavallisen tekstin,
      mutta kaikki muut arvot olisivat class-nimiä, joita on sitten css:ssä sopiva määrä odottamassa.
      Näin ulkoasua voisi muokata paremmin.  Ja sitten vosi olla myös erikseen writeStyle, jolla voisi
      asettaa miltä kirjoitusmuoto näyttää. Itse asiassa readOnly style ja writeStyle voisivat olla
      luetteloita tyyleistä.
* [ ] Save-painike pompaa alemmaksi vähkäsi aikaa ja palaa paikalleen.  Pomppaamisen voisi poistaa.
* [ ]  Taulukkoon tieto onko numeric jolloin syöttö
       mobiileissa helpompaa.  Vähintään toolbariin painike, jolla voi vaihtaa edit-kentän
       numeeriseksi, koska jos yksi on numero, on useimmiten muutkin syötettävät asiat
* [ ]  muukin tapa estää answerbrowser kuin form-mode
* [ ]  jos kenttä on readonly, niin View-tilassa olisi hyvä jos opettaja esimerkin vuoksi
       ei voisi omiakaan muokata, eli näyttäisi samalta kuin opiskelijalle
* [ ]  mahdollisia paperilistoja varten attribuutti jolla voi pyytää loppuun
       n-kpl tyhjiä rivejä  (niihin kirjoittaminen ei tallenna mitään)
* [ ]  tableen myös email (kahdella tavalla, niin että email näkyy ja on lähetys ja niin että
       ei näy, mutta nimi on linkki ja lähetys). Email on jo, linkit puuttuu
* [ ]  tableen ryhmäkäsittely, ks #1430.
* [ ]  jsrunner: mcq ja mmcq vastausten käyttö (muoto on taulukko, eli pitäisi käytännössä saada koko vastaus)
       Pitäisikö laajentaa niin, että voi myös pyytää vastauskentän sisällön sellaisenaan käyttöön
       ja sen voi siten muuttaa json.loads haluamakseen jos tietää muodon
* [ ]  jsrunner ja savebutton toimintojen yhdistäminen (ks selostus alempana)
* [ ]  stylefilters (ks kommentissa)
* [ ]  Kun taulukko näkyy käyttäjälle, niin se näyttää vain sen käyttäjän (toimii OK), mutta soluja ei saisi yrittää turhaan muokata
* [ ]  Molempien desimaalimerkkien (,/.) salliminen
* [ ]  getDouble (myös getInt?) toimimaan tarvittaessa myös tekstiä sisältävällä syötteellä

**Ratkaistut:**

* [x]  Toimiiko globalplugin attribuutit inline plugineille?  Toimii, mutta ei voi laittaa esim `all: cols: 5`
       koska silloin sellaiset pluguinit suuttuvat joissa tuota ei ole.  Olisi kiva jos all:n kautta
       tulevista ei suututtaisi :-)
* [x]  Saako numeric-fieldistä valitsimen pois optiolla? (Saa css:llä, ks alla, mutta suora attribuutti olisi kiva
       ja oletuksena ei nuolia, koska ne vievät tilaa ja hyöty on mitätön)
* [x]  numericfieldistä oletuksena pois näppäin yms rullaus (attribuutilla voi laittaa päälle)
       (ks: https://www.thatstevensguy.com/programming/disable-arrows-on-number-inputs/) 
       Näihin liittyvät attribuutit päällelaittamiseksi:  `arrows: true  wheel: true verticalkeys: true`,
       oletuksena kaikki ovat poissa.  Nuolet ovat vaarallisia, samoin rulla, koska käyttäjä saattaa kuvitella
       rullaavansa näyttöä, ei arvoa.
* [x]  Komponentti ei rekisteröidy jos on labelStyle, pitäisi olla mahdollisuus tällekin (nimeksi readOnlyStyle)
* [x]  Miten teksti komponentin viereen? Vastaus: `inputstem`.  Mutta tämä muutettu niin ettei ole bold.
       Boldia voi tehdä normaaleilla TIMin korostuksillä jos haluaa.  Tosin silloin pitää laittaa lainausmerkkeihin.
* [x]  Miksi fieldit menevät eri riville jos ne on kirjoitettu eri riville.  Näyttää olevan niin, että
       jos rivi alkaa `{#` niin siitä tulee oma rivi.  Jos jotenkin muuten, niin ei tule? 
       Vastaus: Oli ylimääräisiä rivinvaihtoja, poistettu laittamalla strip-metodeja.
* [x]  Taulukon yms automaattinen piilottaminen opiskelijalta jos oikeudet eivät riitä.  Aloitettu
       niin että plugin voi kertoa näkyykö se View-tilassa.  Toistaiseksi toimii vain py-luokasta perityillä
       plugineilla.
* [x]  Taulukkon mahdollisuus että sarakkeiden nimissä ei näytetä docid
* [x]  taulukossa kentät väärässä järjetyksessä (aakkos), pitäisi olla fields-järjestyksessä (poistettu sort)
* [x]  View tilassa sivu näytetään kuten oppilaalle.  Tehty: osin toimii, tosin readonlyssä vielä
       opettajana ollessa voi omia muokata
* [x]  Tapa laittaa fields attribuuttiin useita kenttiä kerralla ettei tarvitse erikseen luetella d1, d2, ...d12
       Voi osin kiertää Jinja silmukalla:  

           %% (' - d{0}\n') | srange(1,democount+1) -%%
 
       Tehty:  
           
           fields: 
               d(1,4)

       tuottaa

           fields: 
               d1
               d2
               d3

       voi antaa myös  `a;b;c`
* [x]  Taulukossa olemattoman kentän tallentaminen ei enää kaada, tallentaa ne mitä voi, mutta tulostaa virheen
* [x]  Opiskelijan nimi näkymään sivulla.  Käytä textfiledissä attribuuttia showname: 1  (realname) tai 2 (username)
* [x]  Templatejen organisointi ja yläkategoroiden vähentäminen oleellisesti
* [x]  Template inline plugineille ja niiden otsikolle jossa näkyy labelina ja editoidaan jollakin
* [x]  tableen myös username optionaaliseksi (tehty muut paitsi toiminta poistamiseksi jos false, oletus true)
       Tehty niin että näytetään hidden columnina
* [ ]  Taulukon rivi nro 2 suodatinriviksi, tai saa tehdä niinkin, että on aina näkyvät inputit html-taulukossa
       vastaaavissa kohti, voi olla helpompi ja niiden viereen pieni sort painike tai sitten se. suodatuksiin myös < ja > 
       operaatiot. Suodattimen tallennus localstorageen. suodattimien tyhjennys.  sort järjestysten tallennus.
       otsikosta klikkaaminen sorttaa koska painikkeesta voi tulla liian ahdas. Tallennukset puuttuu...
* [x]  Taulukon rivi 1 niin, että sen klikkaaminen sorttaa klikatun kentän mukaan kuten Users with answers
* [x]  urlmacros ja paramfields sanitointi (pelkät kirjaimet+numerot, olio parametrina)
* [x]  tableForm oletukeksi singleLine (voi poistaa sitten itse jos haluaa singleLine: false)
* [x]  Opettajan näkymässä henkilön vaihtaminen SIKAhidasta.  Tämä pakko korjata aika KIIREELLISESTI! ks #1420
* [x]  Jos taulukkoa muuttaa ja poistuu sivulta ei tule varoitusta
* [x]  "globaalit" vastaukset, ks. #1417 
* [x]  graafit, ks esim https://tim.jyu.fi/view/tim/ohjeita/visjs, 
       https://tim.jyu.fi/view/kurssit/tie/ohj1/2019k/demot/demot#tilastot
* [x] textfield tallentaa kun siinä käy vaikka ei mitään muuttaisi ja alkupeärinen on tyhjä
* [x]  taulukko tallentaa turhaan nekin arvot jotka ovat samoja kuin aikaisemmin
* [x]  Taulukkoon stylen tallennus (eli jos maalaa soluja, niin ne näkyvät ensikeerran ja myös yksittäisissä soluissa)
* [x]  checkcbox
* [x]  radiobutton ja group (puuttuukohan grop vielä?, group tulee komponentin nimestä)
