### ISSUE TITLE
ViesTIM-projektin (viestilistat, postilistat) jatkokehitys

### ISSUE THREAD

**Issue by dezhidki** [TIM-JYU/TIM#2296]
In GitLab by @totalund on Jun 9, 2021, 16:22

Tässä kortissa on oleellisimmat ViesTIM-projektin jatkokehitystarpeet, kuten projektin vaatimusmäärittelyssä tilassa *Jatkokehitykseen* olevat vaatimukset, järjestelmätestauksessa todetut virheet ja muut tarpeet, jotka ovat oleellisia viestijärjestelmän toimimiseen. Vaatimusmäärittelyssä on myös tiloissaja *Ei projektissa* olevia vaatimuksia, joita ei ole tähän korttiin erikseen vielä nostettu.

[Vaatimusmäärittelyn ](https://tim.jyu.fi/view/kurssit/tie/proj/2021/viestim/dokumentit/vaatimusmaarittely) *Jatkokehitykseen*-tilan tehtävät:

- [ ] Viestilistalla on voitava olla useita omistajia (vaatimus 5.9).
- [ ] TIMistä lähetettyjä yksittäisiä viestejä tulee voida arkistoida lähettäjän henkilökohtaiseen arkistoon (vaatimus 8.7).
- [ ] TIMin tulee arkistoida kukin viesti vain kerran (vaatimus 8.11). Katso TODO [mailman_events.py#L101]( https://gitlab.com/viestim/tim/-/blob/dev/timApp/messaging/messagelist/mailman_events.py#L101).
- [x] TIM-viestin lähettäjän on voitava valita TIM-viestin tärkeys (vaatimus 9.4). Katso TODO [timMessage/routes.py#L304](https://gitlab.com/viestim/tim/-/blob/dev/timApp/messaging/timMessage/routes.py#L304)
- [ ] TIM-viesti tulee voida näyttää valituilla sivuilla jokaiselle niitä katseleville (vaatimus 9.8).
- [ ] TIM-viestin kohdesivujen URL-osoitteissa tulee voida käyttää regexiä (vaatimus 9.10).

Järjestelmätestauksessa ([2. raportti](https://tim.jyu.fi/view/kurssit/tie/proj/2021/viestim/dokumentit/testaus/2.-toiminnallisuustestauksen-raportti)) havaitut virheet, joita projektin aikana ei ehditty ratkaista:

- [ ] Testitapaus 5.13: (Tarkennettava testissä käytettävät syötteet ja testatut tunnukset).

Projektin aikana koodiin kirjoitetut TODO-merkinnät (viittaavat ViesTIM-repoon):

- [ ] Viestilistan jäsenien esitys aakkosjärjestyksessä. Katso TODO [message-list-admin.component.ts#399](https://gitlab.com/viestim/tim/-/blob/dev/timApp/static/scripts/tim/messaging/message-list-admin.component.ts#L399) (TODO merkattu kahteen paikkaan, mutta järjestys kannattaa luonnollisesti tehdä vain yhdessä).
- [ ] Virheenkäsittely / virheen esittäminen käyttäjälle. Katso TODO [messagingUtils.ts#13](https://gitlab.com/viestim/tim/-/blob/dev/timApp/static/scripts/tim/messaging/messagingUtils.ts#L13).
- [x] Muokkaa viestinlähetyskomponenttia niin, että se ei sulkeudu automaattisesti jos vastaanottajakenttä tyhjennetään käsin. Katso TODO [tim-message-send.component.ts#L89](https://gitlab.com/viestim/tim/-/blob/dev/timApp/static/scripts/tim/messaging/tim-message-send.component.ts#L89).
- [ ] Näytä mitä ryhmää TIM-viesti koskee. TODO [tim-message.component.ts#L184](https://gitlab.com/viestim/tim/-/blob/dev/timApp/static/scripts/tim/messaging/tim-message.component.ts#L184).
- [ ] Käsittele mailman-rest-events -kirjaston lähettämä SubscriptionEvent ja UnsubscriptionEvent. Katso TODO [mailman_events.py#L96](https://gitlab.com/viestim/tim/-/blob/dev/timApp/messaging/messagelist/mailman_events.py#L96) ja [mailman_events.py#L99](https://gitlab.com/viestim/tim/-/blob/dev/timApp/messaging/messagelist/mailman_events.py#L99)
- [ ] Sähköpostilistan kautta tullut viesti edelleenlähetetään muihin viestikanaviin. Katso TODO [mailman_events.py#L129](https://gitlab.com/viestim/tim/-/blob/dev/timApp/messaging/messagelist/mailman_events.py#L129).
- [ ] Käyttäjän asettamista yhteystiedoista asetetaan sähköpostilistalle sähköpostiosoitteet oikein. Katso TODO [messagelist_utils.py#L707](https://gitlab.com/viestim/tim/-/blob/dev/timApp/messaging/messagelist/messagelist_utils.py#L707)
- [ ] Kun käyttäjiä lisätään ryhmään tai poistetaan ryhmästä, näiden viestikanavat päivitetään puskuroidusti. Katso TODO [messagelist_utils.py#L745](https://gitlab.com/viestim/tim/-/blob/dev/timApp/messaging/messagelist/messagelist_utils.py#L745) ja [messagelist_utils.py#L767](https://gitlab.com/viestim/tim/-/blob/dev/timApp/messaging/messagelist/messagelist_utils.py#L767).
- [ ] Viestilistan viestiarkiston dokumentin "vain teksti"-asetuksen toteutus. Katso TODO [messagelist_utils.py#L251](https://gitlab.com/viestim/tim/-/blob/dev/timApp/messaging/messagelist/messagelist_utils.py#L251).
- [ ] Viestilistan arkistointitavan muuttuessa viestilistan jäsenet saavat ilmoituksen muutoksesta. Katso TODO [messagelist/routes.py#L184](https://gitlab.com/viestim/tim/-/blob/dev/timApp/messaging/messagelist/routes.py#L184).
- [ ] Kun globaalisti näkyvät TIM-viestit on toteutettu, tarkasta käyttäjän oikeus nähdä dokumentti ennen kuin viesti näytetään. Katso TODO [timMessage/routes.py#L110](https://gitlab.com/viestim/tim/-/blob/dev/timApp/messaging/timMessage/routes.py#L110)

Muut tehtävät (Viestilistat):

- [x] TIM-käyttäjä voi lisätä itselleen muita sähköpostiosoitteita.
  - Liittyy kortteihin #2295 ja #1986
- [x] Autentikointi Postoriukseen TIMin kautta => estetään rekisteröinti suoraan
    * Tämä vaatii pienen [allauth-plugninin](https://github.com/pennersr/django-allauth) toteuttamisen. Aluksi riittää hyvin yksinkertainen menettely (ei tarvitse toteuttaa OAuth-autentikointipalvelua)
- [x] Angular-käyttöliittymän lokalisointi
- [x] Arkistoidun viestin näyttäminen Angular komponentilla suoraan.  Tai oikeastaan komponentit TimArchiveHeader, 
      TimArchiveFooter.  Itse viesti saa olla normaalia "TIMiä", niin sitä voi kommentoida ja muokata
- [x] Hallintakomponentin muuttaminen pluginiksi => siirretään pois pääbundlesta
- [ ] TIM-käyttäjä voi määrätä itselleen sähköpostiosoitteistaan *primääriosoitteen* (primääriosoite on jakeluosoite, kaikki osoitteet ovat lähetysosoitteita).
- [x] TIM-käyttäjän liittyessä viestilistalle (tai lisätessä / poistaessa osoitteitta) hänen viestilistansa päivittyvät automaattisesti.
- [ ] Jos mailmaniin yhteys katkeaa, tulee joko estää kaikki viestilistojen ominaisuudet. Vaihtoehtoisesti tulee pystyä synkronoimaan tiedot, kun yhteys palautuu
- [ ] Selaintestien laajentaminen (ilmoituksen näkyminen tai ei näkyminen tietyillä sivuilla; käyttäjien lisääminen, muokkaaminen ja poistaminen viestilistasta)
- [ ] Lisättäessä jäsentä listalle sähköpostilla tarkastetaan, kuuluuko sähköposti TIM-käyttäjälle. Jos kuuluu, lisätään `MessageListTimMember`-objektina eikä ulkopuolisena jäsenenä.
- [ ] Arkistossa olevaan viestiin vastaaminen TIMillä (voisi lisätä aikanaan Header-komponenttiin?)
- [ ] Kun näytetään listan sivulla valittua ryhmää, voisi olla linkki ryhmän tietojen muokkaukseen
- [x] Käyttöohjeen siirto muiden TIM-ohjeiden luokse.  Linkki ohjeiden sopivan kohtaan itse ohjelmakoodissa.
      Ks mallia esim Tulota dokumentti
- [ ] "Message lists-toiminnon alle: "Jätä sivulle TIM-viesti" ja silloin on automattisesti
      sivun URL-kohdekentässä ja ruksit kun TIM-viestin jättämisessä pitää olla.
- [x] listoja saa tehdä nykyisin vain Group Admin.  Mutta vastaavasti jos on oikeus Sisu-ryhmään, niin
      pitäisi sille ryhmälle saada tehdä lista (ks edellä)
- [ ] Käyttäjän kutsuminen viestilistalle. Katso TODO [messagelist/routes.py#L288](https://gitlab.com/viestim/tim/-/blob/dev/timApp/messaging/messagelist/routes.py#L288). Katso lisäksi TODO [emaillist.py#L338](https://gitlab.com/viestim/tim/-/blob/dev/timApp/messaging/messagelist/emaillist.py#L338) (todennäköisesti TODOssa mainitun lipun voi suoraan asettaa arvolle True ja kutsuminen hoidetaan muilla keinoilla).
    * Myös käyttäjän poistuminen suoraan TIM-käyttöliittymästä
- [ ] #3148
      ryhmän nimi ja jäsäniksi ko ryhmä. Tässä tavassa voisi sallia listan tekeminen, vaikka ei olisi ryhmänteko-oikeutta.
    - Eli listan nimeksi ryhmän nimi (oletusehdotus).
    - oletuksena vain jäsenet saavat lukea arkistoa
    - kuvaukseen että ryhmän xxx lista
    - listan jäseniksi se ryhmä josta lisääminen aloitettiin
- [x] Indikaattori, kun lisätään jäsenet listaan (erityisesti, jos lisätään iso ryhmä)
- [x] Kun uudet jäsenet on lisätty, näytetään ilmoitus, että sivu pitää päivittää => tai sitten päivitetään taulukko automaattisesti
- [x] Saapuneet viestit voisi konvertoida markdowniksi tietyissä osissa
    * Linkkien ympäröinti `<` ja `>` -merkkeihin (saa niistä klikattavat)
    * Lainauksien oikea käsittely
    * Korjataan `eur03.safelinks`-linkit
- [ ] Jotkut paremmat oletukset subscribe/unsubscribe -notifikaatioille
    - Linkki TIM-hallintasivulle
    - Mahdollisesti listan tiedot (esim. lukumäärä)
- [ ] Mahdollisuus konfiguroida viesti, joka lähetetään liittymisestä/poistumisesta
- [ ] jos kurssille tekee postilistoja, ne voisi näkyä kuten kurssin ryhmät vasemman reunan menussa
(tunnistaisikohan ne siitä että joku kurssin ryhmistä on postilistassa)
- [ ] arkistossa voisi olla ettei punaista lukumerkintää tule headeriin eikä footeriin jos saa pienellä vaivalla
- [ ] Dokumenttilistaus TimTableksi
    - Voi suodattaa kaikki sarakkeet
    - Voi valita näytettävät sarakkeet
    - Voi säätää "Last edited"-sarakkeen formattia
- [ ] Jotkin spostilistan asetukset ovat väärin laitettu arkistointivälilehteen
- [ ] Jos lisättävään ryhmään ei ole oikeutta, pitää näyttää virhe
- [ ] Pitäisikö riittää vain view-oikeus ryhmän lisäämiseksi viestilistalle?
- [ ] Jäsenlistauksen laajentaminen
    - TimTable pohjana
    - Voisi näyttää jäsenten lukumäärä (kaikki jäsenet + ryhmät erikseen)
    - Erillinen näkymä, jossa näytetään kaikki jäsenet ja omassa sarakkeessa lista ryhmistä, johon hän kuuluu
- [ ] Bounce-asetus voi olla TIM-käyttöliittymässä
- [ ] Jos käyttäjä on JYU-käyttäjä, niin viestilistaan laitetaan automaattisesti lähetysoikeus kaikkiin mahdollisiin osoitteisiin:
    * `matti.meikalainen@jyu.fi`
    * `matti.meikalainen@student.jyu.fi`
    * `matmeika@jyu.fi` (osoittena käyttäjätunnus)
    * `matmeika@student.jyu.fi`
- [ ] listan arkistoviesteistä linkki itse postilistaan niille, joilla on siihen oikeus
- [ ] kun postilistassa näkyy joku ryhmä joka siihen on liitetty, niitä siitä pääsee klikkaamalla ryhmän asetuksiin
- [ ] postilistan saa perustaa omistajan ryhmän nimelle, eli saa esim postilistan vesal@tim.jyu.fi (tai jopa vesal@tim.pm)

Muut tehtävät (TIMin sisäiset viestit):
- [ ] Ilmoitus saapuneesta viestistä sähköpostitse
- [ ] Viestin otsikko tottelemaan markdownia
- [x] TIM-viestin jättämisen käyttöliittymä ei tarvitse resetoida viestin lähettämisen jälkeen
- [x] viestien lista ei ole aikajärjestyksessä
- [ ] viestien listassa voisi näkyä mikä on kuitattu
- [ ] Viestin peruuttaminen viestidokumentissa
- [ ] Viestin kohdedokumenttien näyttäminen viestidokumentissa
- [ ] Tieto viimeisestä lukukerrasta (eli milloin viimeksi viesti näytettiin) tallentumaan kantaan
- [ ] Viestin poiskuittaus vain viestin yhteyteen laitetulla "salasanalla".
      Käyttötarkoitus:  on kysely johon pakko vastata.  Ko "salasana"
      laitetaan kyselyn loppuun ja sitten kun sen sieltä bongaa, voi
      kuitata viestin pois.  Henkilökohtainen salasana hieman
      haastava, eli aluksi yksi yhteinen (joka heikentää tehoa,
      koska sen voi kysyä kaverilta).
- [ ] Viestit alikansioihin (millä perustein?)
- [ ] Viestien lähetyskomponentti voisi käyttää tavallista lohkoeditoria
      Silloin viestit voi kirjoittaa Markdownilla ja muuntaa Plaintext/HTML -muotoon lähetystä varten
- [ ] Käyttöliittymä uuden TIM-viestin lähettämiseen samalle joukolle TIM-viestidokumentista
- [ ] Mahdollisuus generoida suurempia tilastoja lukeneista ja ei-lukeneista (esim. tunnistetaan, kuka ei ole vastannut pitkään aikaan)
- [ ] Lukeneiden/lukemattomien määrä suoraan TIM-viestikansion ja/tai viestidokumentin näkymään
- [ ] TableForm queryn kopiointipainike sivun valikkoon eikä vastauskomponenttiin
- [ ] Viestin perustiedot näkyviin (tärkeys, umpeutumisaika)
- [ ] Mahdollisuus muuttaa umpeutumisaika ja tärkeys viestin luomisen jälkeen
- [ ] Mahdollisuus lähettää TIM-viestejä automaattisesti tietyille sivuille, kun jollekin tietylle viestilistalle saapuu viesti

Vikoja:

- [x] Käyttäjien mergen yhteydessä tulee varoitus Mailmanilta
- [ ] Jos lähettäjän nimessä on skandit, lähettäjän tiedot menevät sekaisin (häviää spostiosite, tulee ylimääräinen "haamulähettäjä")
- [ ] Listan omistajien/jäsenten päivitys ei välity oikein arkistokansion oikeuksiin
- [x] Next message ei näy Footerissa
- [x] TimTablea odotellessa archives-alla olevat järjestetään id:n mukaisesti (tulisi aikajärjestys)
- [x] arkiston hakemistossa [viesti21] jokaisen viestin edessä ei oikeastaan tuo lisäarvoa? Eli Jos se on Titlessä,
      sen voisi hakemistolistauksessa riisua pois
- [ ] listan muutosviestit voisi tulla "digestinä".  Nyt sain 22 postin ryöpyn ja jos pistää 300
      opiskelijan kurssille, niin tulee aika monta postia.
- [x] ei toteutetut valinnat voisivat olla tekstiltäälkin harmaita niin niitä ei vahingossa
      kokeilisi ruksia päälle/pois
- [x] tein listan ohj21c.  Oikeudet menivät väärin, ks alla
- [x] Listan sivulla `Archive policy:` on otsikkona, mutta sen alla olvat ruksit eivät varmaan kuulu tuolle
      otsikolle.  Minkäs takia arkistointitapaa ei saanutkaan muuttaa? 
  - Arkistointitapaa ei saanut muuttaa, koska sekä muuttamisen toteuttavaa logiikkaa ei ole toteutettu että muutoksesta jäsenille ilmoittavaa logiikkaa ei ole toteutettu -TL.
  - [ ] Sivulta https://tim.jyu.fi/view/messagelists/ohj2k23 pääsee pois ilman varoituksia tallentamatta
- [ ] URLin syöttäminen TIM-viestien lähetyksessä käsin ei toimi, koska parseri syö `/`-merkit pois (ks. esim. #3324)

**Comment by dezhidki** [comment]
Kopioitu #3146:

> Miten löytää helposti kursille luomansa postilistan? Kurssilaisten listaan on kotisivulla linkki.

**Comment by vesal** [comment]
Sivulta https://tim.jyu.fi/view/messagelists/ohj2k23 pääsee pois ilman varoituksia tallentamatta
