### ISSUE TITLE
TIMTra-projektin jatkokehityskohteet

### ISSUE THREAD

**Issue by dezhidki** [TIM-JYU/TIM#2603]
In GitLab by @juaatark on May 12, 2022, 16:11

Tässä on lueteltu sekä jatkokehitykseen siirrettyjä issueita, että ideoita käännöstoiminnallisuuden kehittämiseen tulevaisuudessa. Aluksi esitetään projektissa ratkaisematta jääneet bugit ja issuet, ja niiden jälkeen kaikki jatkokehitykseen siirretyt vaatimukset. Lopuksi voidaan listata muita erityisiä huomioita.

**Ratkaisettomat bugit/issuet**
- [ ] https://gitlab.com/timtra/tim/-/issues/105 Käännöslohko ei siirry mukana, jos alkuperäistä siirretään (siirretty TIMin puolelle https://gitlab.com/tim-jyu/tim/-/issues/2551)
- [ ] https://gitlab.com/timtra/tim/-/issues/238 Yksittäiset hipsut listassa eivät toimi oikein
- [ ] https://gitlab.com/timtra/tim/-/issues/245 Markdown-käsittelyn erikoistapaukset voisi siirtää loogisempaan jäsenninmoduuliin
- [ ] https://gitlab.com/timtra/tim/-/issues/251 DeepL luo uusia erikoismerkkejä erityistilanteissa käännöksen aikana
- [ ] https://gitlab.com/timtra/tim/-/issues/258 DeepL:n kielikoodeille yleisempi käsittely
- [ ] https://gitlab.com/timtra/tim/-/issues/269 Virheilmoitus käyttäjälle kun yritetään luoda käännösdokumenttia kielellä jolle on jo käännösversio 
- [ ] https://gitlab.com/timtra/tim/-/issues/272 DeepL (?) näyttäisi asettavan rivinvaihtoja tietyissä paikoissa Emph- ja Strong-tyylien sisään
- [ ] https://gitlab.com/timtra/tim/-/issues/277 Draggablelle onMinimize-tapahtuma, jolla voidaan käsitellä esikatselunäkymien siirtäminen oikein 
- [ ] https://gitlab.com/timtra/tim/-/issues/278 Tilaajan edustajan palautetta käyttöliittymästä
- [ ] https://gitlab.com/timtra/tim/-/issues/279 Not-null -määrityksen poistaminen DeeplTranslationService:n sarakkeista vaatinee migraatioskriptin
- [ ] https://gitlab.com/timtra/tim/-/issues/281 Käyttöliittymä estää kääntäjän käyttämisen, jos se ei vaadi käyttöavainta
- [ ] https://gitlab.com/timtra/tim/-/issues/286 Makroja ei käsitellä jäsentimessä
- [ ] https://gitlab.com/timtra/tim/-/issues/287 Listan alkioiden väliin tulee joskus käännöksen jälkeen turhia tyhjiä rivejä
- [ ] https://gitlab.com/timtra/tim/-/issues/290 Englannista muihin kieliin kääntäminen hajonnut
- [ ] #3297
- [ ] #3490

**Kehityksen aikana huomioidut asiat, joita ei ole kirjattu vaatimuksiksi tai issueiksi**
- [ ] settings-lohkossa määriteltyjen komponenttien kääntäminen (esim. globaalit plugin-painikkeet yms.)
- [ ] Käännettävien plugin (tyypin mukaan?) -attribuuttien ja LaTeX-tekstiosioiden listauksien (ja tarvittaessa muuten toteutuksen) laajentaminen (projektin aikana huomiotta jääneisiin) käännettäväksi sopiviin
- [ ] kielten listaaminen käyttöliittymässä 
    - [ ] yleisimmin käytettyjä kieliä priorisoiden
    - [ ] aakkosjärjestyksessä?
- [ ] konekääntäjien listaaminen käyttöliittymässä aakkosjärjestyksessä

**Järjestelmätestauksessa ([4.raportti](https://tim.jyu.fi/view/kurssit/tie/proj/2022/timtra/dokumentit/testaus/testausraportit/4.-testausraportti-28.4.2022)) havaitut virheet ja kehitysideat, joita projektin aikana ei ehditty ratkaisemaan**
- [ ] https://gitlab.com/timtra/tim/-/issues/282 Järjestelmätestaukseen tulee lisätä kaksi uutta testitapausta
- [ ] https://gitlab.com/timtra/tim/-/issues/283 YAML-tulkin lisäys pluginien jäsentämisessä
- [ ] https://gitlab.com/timtra/tim/-/issues/284 TIMin pluginien painikkeiden kääntäminen (lokalisaatio)
- [ ] https://gitlab.com/timtra/tim/-/issues/285 Järjestämättömän listan sisennys koodilohkoilla on puuttellinen

**Isoimmat TODO-merkinnät tiedostojen mukaan aakkosjärjestyksessä (viittaavat TIMTra-repoon):**
- [ ] [`timApp/document/translation/routes.py:128`](https://gitlab.com/timtra/tim/-/blob/dev/timApp/document/translation/routes.py#L128): Konekääntäjärajapinta (`TranslationService`) voisi käsitellä poikkeuksia siten, että onnistunut osakäännös voitaisiin saada talteen.
- [ ] [`timApp/document/translation/routes.py:187`](https://gitlab.com/timtra/tim/-/blob/dev/timApp/document/translation/routes.py#L187): Polkufunktiot voisi muuttaa käyttämään `TypedBlueprint`:iä.
- [ ] [`timApp/document/translation/routes.py:538`](https://gitlab.com/timtra/tim/-/blob/dev/timApp/document/translation/routes.py#L538): Käyttöavaimen rekisteröintiä vaativa konekääntäjärajapinta (`RegisteredTranslationService`) voisi toteuttaa avaimen tarkistukseen `validate` tjsp. -metodin.
- [ ] [`timApp/document/translation/translationparser.py:65`](https://gitlab.com/timtra/tim/-/blob/dev/timApp/document/translation/translationparser.py#L65): TIM-liitännäisten (plugin) kokonaisvaltaisemmin kääntämiseksi olisi parempi hyödyntää YAML:ia ymmärtävää jäsennintä nykyisen rivi-avain-arvo -pohjaisen toteutuksen sijasta metodissa `collect_tim_plugin`.
- [ ] [`timApp/document/translation/translationparser.py:499`](https://gitlab.com/timtra/tim/-/blob/dev/timApp/document/translation/translationparser.py#L499): Joidenkin Markdown-elementtien kääntämisen tai kääntämättä jättämisen voisi antaa hienojakoisemmin konekääntäjätoteutuksen päätettäväksi, sillä jäsennin on nyt osin tehty DeepL-kohtaisesti (TODO merkattu useampaan paikkaan ko. moduulia).
- [ ] [`timApp/document/translation/translationparser.py:794`](https://gitlab.com/timtra/tim/-/blob/dev/timApp/document/translation/translationparser.py#L794): Sisäkkäisiä koodilohkoja (esim. kolme \`-merkkiä neljän välissä) ei muodosteta oikein.
- [ ] [`timApp/document/translation/translationparser.py:956`](https://gitlab.com/timtra/tim/-/blob/dev/timApp/document/translation/translationparser.py#L956): Listojen monirivisten arvojen (esim. koodilohko listan alkiona) sisennyksiä ei muodosteta oikein (liittyviä TODO:ita myös moduulissa `timApp/tests/unit/test_translator_parser.py`).
- [ ] [`timApp/document/translation/translator.py:328`](https://gitlab.com/timtra/tim/-/blob/dev/timApp/document/translation/translator.py#L328): Taulukoiden jäsentäminen ilman HTML-muunnosta (joka poistaa "tyylin" kuten *pipes* tai *strokes*) välissä

---

[Vaatimusmäärittelyn](https://tim.jyu.fi/view/kurssit/tie/proj/2022/timtra/dokumentit/vaatimusmaarittely/vaatimusmaarittely) 
_Jatkokehitykseen_-tilan tehtävät

- [ ] Muokkaaja voi valita lähde ja kohdekielen muokastessaan jo käännettyä dokumenttia (vaatimus 1.7)
- [ ] Automaattisesti käännetty osio dokumentista jää välimuistiin, jos sitä ei muokata käännöksen jälkeen (vaatimus 3.7)
- [ ] Muokkaja voi nähdä kuinka paljon dokumenttia on käännetty ja mihin kieliin. (vaatimus 3.8)
- [ ] TIM ilmoittaa kun dokumenttia on käännetty paljon. (vaatimus 3.9)
- [ ] Kielivalinnoissa kielinimien kielten viereen merkitään kyseisten kielten maiden liput. (vaatimus 3.12)
- [ ] Avainten hallinta organisaatiotasolla. (tarkennettava) (vaatimus 6.1)
- [ ] TIMiin mahdolliseksi rajata API-avainten käyttö vain tiettyihin dokumentteihin. (tarkennettava)(vaatimus 6.2)
- [ ] Moduuli korjaa käännöksen aiheuttamat systemaattiset virheet. (vaatimus 9.2)
- [ ] TIMissä on mahdollista nähdä kolme eri ikkunaa kolmelle eri käännökselle. (vaatimus 10.6)
- [ ] TIMissä on pikanäppäin linkin lisäämiselle. (vaatimus 10.7)
- [ ] Käännettäessä jo kertaalleen käännettyä tekstiä, käännös tulee vain niihin sanoihin jotka ovat muuttuneet. (vaatimus 10.8)
- [ ] Käyttäjä voi avata vaihtoehtoisia käännöksiä kohdekielelle ja tarkastella niitä. (vaatimus 10.9)
- [ ] Muokkaaja voi käyttää termipankkia käännöstyössä. (vaatimus 11.1)
- [ ] Ylläpitäjä voi lisätä sanoja tiedekunnan termipankkiin. (vaatimus 11.3)
- [ ] Opettaja voi lisätä sanoja kurssin termipankkiin. (vaatimus 11.4)
- [ ] Tiedekunnilla ja/tai kursseilla omat termipankit. (vaatimus 11.5)
- [ ] Muokkaaja voi käyttää vakiosanastoa käännöstyössä. (vaatimus 12.1)

**Muita toivomuksia ja kohtia, joita on kirjattu jälkikäteen**

- [ ] Editorissa olevaa käännöspainiketta kannattaa näyttää vaikka ei olisi käännösdokumentissa
       Käyttötapaus: kirjoittaa jotain suomenkielistä dokumenttia ja haluaa helposti kääntää jotain pastettua englanninkielistä tekstiä.

Pohdintaa:

Pitäisikö olla translate tyyli, joka pakottaa käännöksen? Syynä esimerkkinä koodilohkot, eli alueet joita ei voida ilman käyttäjän lupaa kääntää.
