### ISSUE TITLE
KATTI-projektin jatkokehityskohteet

### ISSUE THREAD

**Issue by dezhidki** [TIM-JYU/TIM#2646]
In GitLab by @immomipe on Jun 13, 2022, 09:55

Kiirellisimmät korjaukset:

- [ ] Bookkaus helpommaksi: mahdollisuus ohittaa OK painike.  Lisäksi OK ei toimi Enterillä, vaan luo uusia OK-dialogeja.
- [x] kalenterin aikaväli (oletus 20 min) attribuutiksi ja myös 120 min valintalistaan
- [x] oletusnäkymä attribuutiksi
- [x] aloitusaika attribuutiksi (nyt aika nykypäivä).  Jos on esim pääteohjaus sivulla viikon 42
       varaukset, olisi luonnollista näyttää viikkoa 42, ei nykyviikkoa.
- [x] attribuutiksi voiko viestin lähettää.  
- [ ] Mahdollisuus lisätä henkilöt tai ryhmät tapahtumaan heidän puolesta
- [x] Em koskee myös Vie-kalenteria. Siellä saisi näkyvä vain sellaiset joissa on itse mukana ellei
       tapahtuman attribuuteilla muuta pakoteta. 
- [ ] HT-ohjauksista vain varatut ja varaajan nimi pitäisi näkyä
       viedyssä tapahtumassa
- [ ] valittavaksi mistä tapahtumatyypeistä tulee sähköpostia, esim jos laittaa luennon ja
      jokaisesta liittyneestä tulee, niin saa aika paljon postia.  Oletuksena noista jossa on
      HT-ohjaustyylinen juttu, että periaatteessa yksi varaa, mutta voi liittää kavereita
- [ ] Bugi: jos kalenterissa ei ole tietyn tapahtumatyypin kohdalla ryhmää kun tapahtuma tehdään
       (tai joku ryhmä puuttuu), niin ryhmän korjauksen (lisäämisen) jälkeen tapahtuma ei ilmesty
      ryhmäläisten kalenteriin.  Tulee vasta jos tapahtuman poistaa ja lisää uudelleen.
      Vastaavasti jos jonkin ryhmän poistaa tapahtumasta, niin se ei poistu ryhmälaisten kalenterista.
      Mikäli tapahtumaan on "liimattu" kiinni ne ryhmät ja plugin asetus on vain oletus, niin ryhmät
      saisivat näkyä tapahtuman muokkauksessa ja ihannetilanteessa niitäv oi siinä muokata.
      Mutta jos ryhmälista muuttuu pluginin kautta, niin voi olla että on jo tehty kymmeniä tapahtumia
      "väärillä" ryhmillä ja pitäisi vähintään kysyä, että muutetaanko kaikki ko tyypin tapahtumat
      samalla tavalla.  Sama ongelma tosin muidenkin Event template arvojen kanssa. 
      Esim Title ei vaihdu kun sitä vaihtaa (tuleeko ongelmia kääntämisessä??)
- [x] Paikan oletus pitäisi saada EventTemplateen jotta esim luentoja laittaissa ei tarvitsisi
       joka kerta salia naputella.
- [ ] Templateen optio että lisätäessa avataan dialogi (jos haluaa aina vaihtaa otsikon, tulee työlästä)
- [x] Teksti (JSON) tms muotoinen tapa muokata koko kalenterisettiä.  Nyt esim haluaisin tehdä
       tapahtumia nimillä Luento 01, Luento 02, Demo 01, Demo 02, ... jne ja siitä tulee kauhean työlästä.
       Tämä voisi olla alustava tapa myös muokata tapahtumien attribuutteja.
- [ ] Kalenterin dialogin aikaformaattina on USA tyyli 08/16/22 ja kellona 2:00 PM, saisi olla fi tyyli
- [ ] Dialogi saisi tallentua Ctrl-S kuten csPlugin ikkunat
- [ ] Pitäisi voida antaa attribuuttiehin oletusalku ja loppu min, eli mulla tulee paljon 12:15-13:45
       ja nyt joutuu aina menemään korjaamaan aikoja (olisiko joku `defStartMin: 15`, `defEndMin: -15`
- [ ] Kalenterin ICS:ään voisi ohjaustapahtumissa jotenkin ujuttaa varanneiden nimet
- [ ] jos on asettanut ohjausajan ja joku on sen bookannut, niin se ei ola "vihreä" (ei näy muissa kalentereissa eikä ics)
- [x] #3152

Muuta korjattavaa:

- [ ] Tapahtumalla voisi olla URL niin saisin esim luento-tapahtumasta menemään
suoraan oikealle luennolle.
- [ ] Näkymän enrolment-määrät.  Esim attribuutti

           enrolmentCounts:
                - ohj1s22paate
                - ohj1s22eta

     tulostaisi jotakin tyyliin:

               ohj1s22paate: 45/30    # 45 varausta, 30 eri varaajaa
               ohj1s22paate: 53/18 
                
     Tosin tätä voisi hoitaa niinkin, että jsRunner voisi tilata kalenterin jsonin käytettäväksi      ja laskisi nuo jsrunnerilla
- [ ] massamuokkausta avustavia funktioita tools-olioon. Mm. ne aikavyöhykksseen liittyvät
- [ ] kun tapahtumaa klikataan, voisi hakea uusimmat tiedot palvelimelta jos on tullut viestejä, tila tullut täyteen tms
- [ ] jos tapahtuma alkaa x:15 ja aikajako on 120 min, niin tuon kanssa seuraava vaikka (x+2):00 alakva ei mahdu
       alekkain.  Joku pitää pikkuisen korkeudesta tinkiä tai x:15 ei pudoteta niin paljon alaspäin.
- [x] kalenterin alku- ja loppuaika attribuutiksi
- [ ] Massamuokkauksen filtterit muokkausdialogiin, oletukset kalenterin mukaan
- [ ] massamuokkaus myös tapahtuman muokkausdialogista
- [ ] massamkuokkaukseen menvät tapahtumat voi valita valitsemalla jollakin tavalla monta tapahtumaa
- [ ] kun ilmoittautuu tapahtumaan, määrälaskuri ei päivity ennenkuin virkistää selaimen
- [ ] jos useita aikoja samassa "solussa", niin ilmoittautuneiden määrä ei näy (hätätilassa päivänäkymä auttaa)
- [ ] jos aloituspvm attribuutti on olemassa, niin silloin nykypvm kaveriksi siirry attribuutin pvm
- [ ] kuukausinäkymään viikkonumerot
- [ ] tekstilaatikko Korpin tapaan, johon saa kirjoittaa mihin pvm haluaa hypätä (attribuutille voi
       tuoda näkyviin. Korpin tapaan tukee muotoka  
           - 12 (hyppää kuluvan kuun 12. pv)
           - 12.9 (hyppää kuluvan vuoden 12.9)
           - 12.10.23 (hyppää 12.10.2023)
           - v46  (hyppää viikon 46 ma)
           - v46 ke (hyppää  viikon 46 keskiviikkoon)
           - w47 (kuten edellä)
           - w47 we (kuten edellä)
           - tyhjä hyppää kuluvaan pvm 
- [ ] tapahtuman tyyppiin väri attribuutiksi, sekä vapaa väri että täysi väri että itselle otettu väri
- [ ] käyttöohjeessa oleva filtteröinti kuntoon
- [ ] kalenterin yläpuolella oleva osuus kompaktimmaksi (pienemmät painikkeet, paikkojen suunnittelua)
- [ ] tapahtumatyyppi (lähinnä kun lisätään omia tapahtumia tms), joka blokkaa jo laitetut esim
       HT-ohjausajat niin, ettei niitä voi varata.
- [ ] sitten kun kalenterin tuonti on kunnossa, pitää miettiä millä ehdoilla tuodut tapahtumat
       blokaavat HT-ohjauksia
- [ ] bookkaussähköpostissa voisi olla käyttäjätunnuksen lisäksi myös oikea nimi.
- [ ] Tapahtuman lisääminen niin, että voi sanoa että tätä laitetaan joka viikolle 13 viikon ajan
       (juhlapyhävaroitus, ei saisi mennä sellaisen päälle).
      (isoin haaste miten tuolloin saisi nimiä tyyliin Luento 01, Luento 03 jne...)
- [ ]  pieni kauneusvirhe: määrälaskurit eivät päivity bookkauksen jälken ennen
        refreshiä
- [ ] pitäisikö extrabookkaajalle aina ilmoittaa että hänestä tulee "ohjaaja".
        kunnes tulee joskus tulevaisuudessa kl missä saa valita, minkä
        bookkauksen tekee jos on oikeuksia moneen erilaiseen
- [ ] Tapahtuman luoja voisi näyttää tapahtuman tiedoissa. Vähintään pitäisi olla mahdollisuus määrittää "vastuuhenkilö", jonka yhteystiedot näytetään tapahtumassa

      Vastuuhenkilö siis voi olla eri kuin tapahtuman luoja. Tapahtuman luojaa ei olisi aina järkevää näyttää, koska se voi olla joku kokonaan tapahtumaan kuulumaton, ja koska tapahtumaa voi kuitenkin muokata muutkin kuin luoja. Esimerkiksi tuntiopettaja laittaa kurssille luentoaikoja, jolloin tuntiopettajan yhteystietojen laittaminen on turhaa ja voi jopa häiritsevää tuntiopettajalle -> yhteystietona pitäisi olla opettaja. TAI pitäisi pystyä siihen, että opettaja voi valtuuttaa tuntiopettajaa laittamaan tapahtumia, jolloin tapahtuman omistajaksi tulee opettaja.
    Tapahtuman todellinen luoja voisi näyttää loppujen lopuksi edit-tilassa, eli setterit näkevät hänen tiedot. bookerit voivat sitten nähdä jonkun "vastuuhenkilön".

*** 

Tästä jatkuu  oleellisimmat KATTI-projektin jatkokehitystarpeet, kuten projektin vaatimusmäärittelyssä tilassa _Jatkokehitykseen_ ja _Ei projektissa_ olevat vaatimukset.

[Vaatimusmäärittelyn](https://tim.jyu.fi/view/kurssit/tie/proj/2022/katti/dokumentit/vaatimusmaarittely) Jatkokehitykseen -tilan tehtävät:

- [ ] Opiskelija voi tapahtumia hakiessaan valita tarkasteltavaksi kurssin kaikki ohjaajat tai yksittäisen ohjaajan. (Vaatimus 2.4) https://gitlab.com/jopitikk/tim-katti/-/issues/14

- [ ] Opiskelija voi ilmoittaa varaamaansa tapahtumaan ryhmän, johon voi liittää esim. työparinsa (tarkennettava). (Vaatimus 2.5) https://gitlab.com/jopitikk/tim-katti/-/issues/15

- [ ] Tapahtumaa varattaessa kalenterissa näkyvät opiskelijan muut TIMiin kirjatut tai muista kalentereista tuodut tapahtumat. (Vaatimus 2.11) https://gitlab.com/jopitikk/tim-katti/-/issues/61 

- [ ] Opiskelija saa halutessaan sähköpostiin ilmoituksen varaamastaan tapahtumasta.	(Vaatimus 2.15)

- [ ] Kurssin opettaja voi ilmoittautua opetusryhmään ohjaajaksi. (Vaatimus 4.2) https://gitlab.com/jopitikk/tim-katti/-/issues/24

- [ ] Kalenterinäkymä muuttuu valitun kielen mukaan (FI, EN).	(Vaatimus 5.8) https://gitlab.com/jopitikk/tim-katti/-/issues/31

- [ ] Kalenteriin voi tuoda informaatiota ICS-formaatin avulla muista kalentereista. (Vaatimus 6.2) https://gitlab.com/jopitikk/tim-katti/-/issues/21

[Vaatimusmäärittelyn](https://tim.jyu.fi/view/kurssit/tie/proj/2022/katti/dokumentit/vaatimusmaarittely) Ei projektissa -tilan tehtävät:

- [ ] Tapahtumia lisättäessä menneeseen aikaan tulee ilmoitus. (Vaatimus 1.7) https://gitlab.com/jopitikk/tim-katti/-/issues/35 https://gitlab.com/jopitikk/tim-katti/-/issues/68

- [ ] Ryhmä saa sähköpostiin ilmoituksen varatusta ajasta. (Vaatimus 2.6) https://gitlab.com/jopitikk/tim-katti/-/issues/22

- [ ] Opiskelija voi varata vain tietyn määrän tapahtumia viikossa (tarkennettava). (Vaatimus 2.10) https://gitlab.com/jopitikk/tim-katti/-/issues/17

- [ ] Ohjaaja saa halutessaan sähköpostiin ilmoituksen varatusta tapahtumasta ICS-tiedostona. (Vaatimus 2.13)

- [ ] Opiskelija saa halutessaan sähköpostiin ilmoituksen varaamastaan tapahtumasta ICS-tiedostona. (Vaatimus 2.16)

- [ ] Ohjaaja voi varata ohjaustapahtuman opiskelijalle (tarkennettava). (Vaatimus 2.17)

- [ ] Ohjaaja näkee kalenterista ohjaustapahtumaan ilmoittautuneiden opiskelijoiden ja ohjaajien lukumäärän. (Vaatimus 4.4) https://gitlab.com/jopitikk/tim-katti/-/issues/26

- [ ] Opiskelija näkee kalenterista ohjaustapahtumaan ilmoittautuneiden opiskelijoiden ja ohjaajien lukumäärän. (Vaatimus 4.5)

- [ ] Kellonaikamuotoa voi vaihtaa kielestä riippumatta. (Vaatimus 5.9) https://gitlab.com/jopitikk/tim-katti/-/issues/32

- [ ] Kalenterinäkymäksi voi valita myös vuosinäkymän. (Vaatimus 5.10) https://gitlab.com/jopitikk/tim-katti/-/issues/33

- [ ] Vapaapäivät ja arkipyhät näkyvät kalenteripohjassa eri värillä. (Vaatimus 5.11) https://gitlab.com/jopitikk/tim-katti/-/issues/34

- [ ] Varattavissa olevan tapahtuman varaamisessa on aikakatkaisu jolloin dialogia täyttäessä toinen ei kerkeä varaamaan samaa aikaa. (Vaatimus 5.13) https://gitlab.com/jopitikk/tim-katti/-/issues/69

- [ ] Kalenterin avulla voidaan varata muitakin resursseja kuten laitteita. (Vaatimus 7.1) https://gitlab.com/jopitikk/tim-katti/-/issues/36

- [ ] Ohjaaja voi tehdä itselleen profiilin, jossa on ohjaajasta tietoina mm. kuva, kielitaito ja tekninen osaaminen. (Vaatimus 7.2) https://gitlab.com/jopitikk/tim-katti/-/issues/37

- [ ] Opiskelijalla on oikeus nähdä kurssinsa ohjaajien profiilit. (Vaatimus 7.3)

Muut jatkokehityskohteet:

- [ ] Tagien filtteröinti esim. regexilla tai yksinkertaisella wildcard-tarkistuksella
- [ ] Attribuutti tapahtumapohjaan, jolla kerrotaan, että tapahtuman luoja ilmoittautuu tapahtumaan automaattisesti
- [ ]  Tapahtuman ilmoittautumispainike myös Edit-näkymän tapahtumadialogiin
- [ ] Kalenterista on mahdollista piilottaa täyteen bookatut tapahtumat
- [ ] Mahdollisuus "jonottaa" ilmoittautumista https://gitlab.com/tim-jyu/tim/-/issues/1791
- [ ] Luentojen yms. tapauksessa pitäisi olla helppoa myös ilmoittautua kaikille kurssin luentokerroille https://gitlab.com/tim-jyu/tim/-/issues/1791
- [ ] Tapahtumien lisääjällä kalenterissa näkyy taustalla omat muut tapahtumat https://gitlab.com/tim-jyu/tim/-/issues/1791
- [x] Kalenterissa näytettävän ajankohdan määrittäminen markupin `filter`-attribuuttien avulla. (Esim. jokaisella ohjaussivulla aloitetaan kyseisen ohjauksen viikosta näyttäminen.)
- [x] Kalenterissa oletuksena näytettävän näkymän määrittäminen markupin attribuuttien avulla. (Päivänäkymä/ Viikkonäkymä/ Kuukausinäkymä)
- [x] Kalenterin minuuttijaon määrittäminen markupin attribuuttien avulla (esim. 60min, jolloin näkymä on suoraan kompaktimpi).
- [ ] Viestimistä voisi asettaa erikseen että kuka saa laitata viestiä.  Tapahtuman omistaja
  vai myös bookkautuneet.  Käyttötapauksena voisi olla että luennoille tms
  haluttaisiin laittaa joku viesti.  Ja jossakin vähän pienemmässä tilanteessa
  voisi jopa olla toivottavaa että ilmoittautuneet viestisivät keskenään
  jostakin.   Mutta silloin tätä saisi säätää ihan kuten haluaa.  Oletukset
  sitten tuon tullessa voisivat olla juuri kuten nyt, eli oletuksena ei
  viestintää paitsi yhden hengen tapahtumissa.
- [ ] #3221
- [ ] Massamuokkaus voisi antaa tarkan rivinumeron ja kohdan, jos mukana on JSON-syntaksivirhe. Toistaiseksi tulee vaan selaimen oletusvirhe mallia `SyntaxError: Bad control character in string literal in JSON at position 3896`

Projektin aikana koodiin kirjatut TODO-merkinnät:

- [ ] Varaajan tapahtumaan jättämät viestit käytössä nyt vain yhden henkilön varaamissa tapahtumissa:
[calendar-event-dialog.component.ts#L411](https://gitlab.com/jopitikk/tim-katti/-/blob/master/timApp/static/scripts/tim/plugin/calendar/calendar-event-dialog.component.ts#L411)
[calendar-event-dialog.component.ts#L464](https://gitlab.com/jopitikk/tim-katti/-/blob/master/timApp/static/scripts/tim/plugin/calendar/calendar-event-dialog.component.ts#L464)
[calendar-event-dialog.component.ts#L664](https://gitlab.com/jopitikk/tim-katti/-/blob/master/timApp/static/scripts/tim/plugin/calendar/calendar-event-dialog.component.ts#L664)
- [ ] Päivämäärä-suodattimen oikea tyypitys, kun suodattimet otetaan käyttöön:
[calendar.component.ts#L97](https://gitlab.com/jopitikk/tim-katti/-/blob/master/timApp/static/scripts/tim/plugin/calendar/calendar.component.ts#L97)
- [ ] Tapahtumien suodattaminen kalenterinäkymässä käyttäjän tekemien valintojen mukaan:
[calendar.component.ts#L193](https://gitlab.com/jopitikk/tim-katti/-/blob/master/timApp/static/scripts/tim/plugin/calendar/calendar.component.ts#L193) 
[calendar.component.ts#L319](https://gitlab.com/jopitikk/tim-katti/-/blob/master/timApp/static/scripts/tim/plugin/calendar/calendar.component.ts#L319)
[calendar.component.ts#L434](https://gitlab.com/jopitikk/tim-katti/-/blob/master/timApp/static/scripts/tim/plugin/calendar/calendar.component.ts#L434)
- [ ] Raahattaessa uutta tapahtumaa, sen maksimikoko on raahauksen ajan aina yksi:
[calendar.component.ts#L475](https://gitlab.com/jopitikk/tim-katti/-/blob/master/timApp/static/scripts/tim/plugin/calendar/calendar.component.ts#L475)
- [ ] Tapahtumien meta-datan käsiteltävä oikeaoppisesti:
[calendar.component.ts#L545](https://gitlab.com/jopitikk/tim-katti/-/blob/master/timApp/static/scripts/tim/plugin/calendar/calendar.component.ts#L545)
- [ ] Käytöstä poistettu funktio, jonka avulla tapahtuman ajankohta voidaan esittää tapahtuman otsikossa:
[calendar.component.ts#L557](https://gitlab.com/jopitikk/tim-katti/-/blob/master/timApp/static/scripts/tim/plugin/calendar/calendar.component.ts#L557)
[calendar.component.ts#L558](https://gitlab.com/jopitikk/tim-katti/-/blob/master/timApp/static/scripts/tim/plugin/calendar/calendar.component.ts#L558)
- [ ] Turhaksi (mm. koodikatselmoinnissa) nähty koodirivi, jonka komponentti kuitenkin vaatii toimiakseen odotetunlaisesti:
[calendar.component.ts#L582](https://gitlab.com/jopitikk/tim-katti/-/blob/master/timApp/static/scripts/tim/plugin/calendar/calendar.component.ts#L582)
- [ ] Tietokantakyselyt kaipaavat refaktorointia:
[calendar.py#L204](https://gitlab.com/jopitikk/tim-katti/-/blob/master/timApp/plugin/calendar/calendar.py#L204)
- [ ] Lähetettyjen sähköpostien aikaleimojen tulisi huomioida käyttäjän aikavyöhyke:
[calendar.py#L538](https://gitlab.com/jopitikk/tim-katti/-/blob/master/timApp/plugin/calendar/calendar.py#L538)
[calendar.py#L650](https://gitlab.com/jopitikk/tim-katti/-/blob/master/timApp/plugin/calendar/calendar.py#L650)
- [ ] Muille kuin käyttäjän henkilökohtaisille ryhmille tehtävien tapahtumavarausten implementointi:
[calendar.py#L580](https://gitlab.com/jopitikk/tim-katti/-/blob/master/timApp/plugin/calendar/calendar.py#L580)
- [ ] Nykyään kaikki varaukset ovat tyypiltään 'booking'. Muiden varaustyyppien lisääminen:
[calendar.py#L606](https://gitlab.com/jopitikk/tim-katti/-/blob/master/timApp/plugin/calendar/calendar.py#L606)

**Comment by vesal** [comment]
## Liikojen aikojen karsinta

Tein kaksi dokumenttia ja niihin kalenterit:

- <https://tim.jyu.fi/view/kurssit/tie/ohj1/2022s/tuntiopettajat>
- <https://tim.jyu.fi/view/kurssit/tie/ohj1/2022s/ohjaukset/paateohjaus1>

Yritin saada niin, että tuntiopettajien kalenterissa näkyisi vain HT-ohjausten varaaminen
ja paateohjaus-kalenterissa vain pääteohjaukset ja luennot.

Nuo pitiäisi mielestäni saada niin, että esim tuntiopettajien kalenterista opiskelija ei näe pääteohjauksia
ELLEI ole ilmoittautunut ohjaksiin.  Eli aina näkyisi oletuksena vain ne mitä on lueteltu ja
sitten omat "aktivoidut".  Kalenteria attribuuteilla tätä voisi sitten muuttaa tarvittaessa.

**Comment by dezhidki** [comment]
## Varaamisen yleistäminen, varaustyypit ja "resurssit"

Kopioitu Vesan viestistä sellaisenaan, eli ei vielä sortattu (tai jaettu omaan korttiin):

"ison" kalenterin myötä tuleekin kysymys, että pitäisikö bookkauksia
olla useanlaisia?  Ja monenkolaisia?  Tässä käyttötapauksessa siis
oppiskelijana ja ohjaajana.

Selvittäisiin yhdellä kalenterilla jos olisi noin.

Ja silloin noita kapasiteetteja voisi näyttää jotenkin tyyliin

  15/30/3

joka tarkoittaisi että on 15 oppiskelijabookkausta, 30 tilaa ja 3
ohjaajabookkausta.

Se helpottaisi noiden kalentereiden tekemistä, kun ei tarvitse silloin
toistaa kaikkia tapahtumia opettajien kalenteriin.

Mutta keksiikö joku sitten vielä lisää noita bookkaustyyppejä?
Eli esim opiskelija/ohjaaja/opettaja (eli tapahtumassa on opsikeijoita,
avustavia ohjaajia ja pitää olla vielö yks virallinen opettaja.

Voiko HT ohjausaikoja tehdessä tulla tilanne, että joku laittelisi
varattavia aikoja ja sitten sinne jonnekin menee opiskelija ja sitten joku
ohjaaja bookkaa sen tapahtuman itselleen.

Toki se nykyinen onnistuu, että ohjaajat laittavat aikoja ja opiskeijat
bookkaaavat niitä itselleen, eli tähän käyttötarkoitukseen edellinen
oli huono esimerkki.

Menisikö tuo eventtemplatessa esim tyyliin:

    evetTemplates:
       Pääte:
         capacity: 30
         bookers:  # opiskelijat
           - ohj1s22
         extraBookers:
           ohjaajat:
             - ohj1
           opettajat:
             - ohj1opet


ja sitten nuo extrojen määrät näytettäisiin sen 15/30 perään.

Jos joku kuuluu useampaan noista bookkausryhmistä, niin
silloin bookkausta tehdessä pitäisi valita missä roolissa
on menossa.

Joskus tulevaisuudessa voisi olla joku tapa ilmoittaa "hoitajamitoitus",
eli laatis noihin extraBookers-kohtiin säännöt, joilla tapahtumn väri
on erilainen jos mitoisut ei täyty tai ylittyy.  Esim jotenkin sanoa,
että pitää olla yksi ohjaaja/6 opiskelijaa tms.  Muta nyt tuota hoidetaan
toistaiseksi "silmällä".

**Comment by dezhidki** [comment]
## Tapahtumien export ja import JSONilla

Kopioitu Vesan viestistä:

Aluksi se voisiolla ihan iso ACE-ikkuna, johon tulisi pyydetty
tapahtuma/t JSONIna ja kun sen lähettää tai monistaa useammaksi
tapahtumaksi, niin ne käsitellään.

Silloin voisin esim luennot yms toistuvat tehdä niin,
että haen sen ekan pohjaksi, teen apudokumentissa
makroilla ja forilla JSONin jossa on sitä eka amonistettu
muille päiville, kopioin takaisin ja POSTaan sen sitten.

Ja sama demojen monistamiselle.

Ja tuosta voisi periaattessa sitten kehittää muöhemmin tavan tehdä sivu, jossa
on parametrina alkua ja loppua ja toistoehtoa yms.

Keväällä ongelmaksi tulee juhlapyhät (mm pääsiäinen) joiden lista
pitäisi saada käyttöön että niitä voidaan ohittaa.  Tosin ohj2:ssa on
"vain" tuo pääsiäinen, joten sen voi ottaa kovakoodattuna huomioon
siinä omassa forissa.  Itse asiassa mulla on preamblessa lueteltu demojen yms
päivämäärät, niin voisin käyttää niitä siinä generoivassa forissa niin
ei tarvitsisi toistaa.

**Comment by vesal** [comment]
Päivänäytössä:

https://tim.jyu.fi/view/kurssit/tie/ohj1/2022s/ohjaukset/paateohjaus?nr=4

ei voi vaihtaa tuntijakoa
