### ISSUE TITLE
TIMath jatkokehityskortti

### ISSUE THREAD

**Issue by dezhidki** [TIM-JYU/TIM#3426]
Tämä kortti sisältää TIMath-projektin (#3368) jatkokehityskohdat.

# Ratkaisemattomat bugit/issuet

- [ ] https://github.com/TIMath23/TIM/issues/89 Preview becomes zero sized during its updating
- [ ] https://github.com/TIMath23/TIM/issues/157 
- [ ] https://github.com/TIMath23/TIM/issues/159
- [ ] https://github.com/TIMath23/TIM/issues/200
- [ ] https://github.com/TIMath23/TIM/issues/246
- [ ] https://github.com/TIMath23/TIM/issues/238
- [ ] https://github.com/TIMath23/TIM/issues/241
- [ ] https://github.com/TIMath23/TIM/issues/240
- [ ] https://github.com/TIMath23/TIM/issues/188
- [ ] https://github.com/TIMath23/TIM/issues/51
- [ ] https://github.com/TIMath23/TIM/issues/222
- [ ] https://github.com/TIMath23/TIM/issues/148
- [ ] https://github.com/TIMath23/TIM/issues/12
- [ ] https://github.com/TIMath23/TIM/issues/129
- [ ] https://github.com/TIMath23/TIM/issues/175
- [ ] https://github.com/TIMath23/TIM/issues/176
- [ ] https://github.com/TIMath23/TIM/issues/177
- [ ] https://github.com/TIMath23/TIM/issues/178
- [ ] https://github.com/TIMath23/TIM/issues/179
- [ ] https://github.com/TIMath23/TIM/issues/243
- [ ] https://github.com/TIMath23/TIM/issues/245
- [ ] https://github.com/TIMath23/TIM/issues/226
- [ ] https://github.com/TIMath23/TIM/issues/233

# Testauksessa havaitut virheet ja kehitysideat, joita projektin aikana ei ehditty ratkaisemaan
[1. testausraportti](https://tim.jyu.fi/view/kurssit/tie/proj/2023/timath/dokumentit/testaus/testausraportit/1.-testauskerran-raportti)
- [ ] Kaavaeditori ilmestyi järjestely-esimerkkiin, vaikka siinä ei ole tekstikenttää käytössä.
- [ ] Lohkoeditorin TeX-välilehdessä voi lisätä kaavaeditoriin niin monta riviä, että lohkoeditorin alaosaan ei enää pääse sivua vierittämällä. Tämä on ongelma pääosin pienissä dokumenteissa joissa on vähemmän tilaa.
- [ ] Mahdollinen ongelma jos kaavassa on \begin{align*}\begin{cases} jolloin sitä ei voi muokata.

[2. testausraportti](https://tim.jyu.fi/view/kurssit/tie/proj/2023/timath/dokumentit/testaus/testausraportit/2.-testausraportti-15.5.2023)
- [ ] Jos lisää latexButtonsEditable-attribuutin lohkoeditorissa kun Ace editor ei ole päällä, niin painikkeet eivät toimi. Ks. https://github.com/TIMath23/TIM/issues/241
- [ ] TIM-painikkeen tekstillä ei ole maksimipituutta joten se voi mennä editorin ulkopuolelle.
- [ ] Kaavaeditorin rivien välillä siirtyminen ei toimi oikein tablettitietokoneella.
- [ ] Tablettitietokoneella perumisen ja toistamisen pikanäppäimiä ei voi käyttää. Ks. https://github.com/TIMath23/TIM/issues/238

[3. testausraportti](https://tim.jyu.fi/view/kurssit/tie/proj/2023/timath/dokumentit/testaus/testausraportit/3.-testauskerran-raportti-20.5.2023)
- [ ] Lisätyn painikkeen virheellinen LaTeX näyttäytyi erittäin suurikokoisena punaisena tekstinä, ja itse painike oli myös muita painikkeita paljon suurempi. Ongelma korjaantui kun sivun latasi uudelleen.
- [ ] Keskeneräisen kaavan syötteitä ei voi perua tai toistaa graafisessa syötealueessa, koska se tallentuu vain LaTeX-syötealueeseen.
- [ ] Mahdollinen ongelma kaavan muokkaamisessa lohkoeditorissa, ongelmaa ei kuitenkaan saatu toistettua testauskerran jälkeen. Ehkä liittyy https://github.com/TIMath23/TIM/issues/222.

# Vaatimusmäärittelyn jatkokehityskohteet

[Vaatimusmäärittely](https://tim.jyu.fi/view/kurssit/tie/proj/2023/timath/dokumentit/vaatimusmaarittely/vaatimusmaarittely)

- [ ] TIM:iin lisätään matematiikkaeditori uutena editorityyppinä.
- [ ] Symbolipainikkeet renderöidään SVG:ksi Dumbolla tai Pandocin avulla.
- [ ] Mahdollisuus lisätä dropdown-valikoita symbolipainikkeille.
- [ ] Esikatselun voi siirtää tehtäväeditorin viereen. Ks. https://github.com/TIMath23/TIM/issues/200
- [ ] Perumis- ja toistotoiminnoilla on omat painikkeensa. Ks. https://github.com/TIMath23/TIM/issues/238
- [ ] Kuvan resoluutiota tehtäväeditorissa voi säätää. 
- [ ] Kuvaa voi kiertää tehtäväeditorissa. 
- [ ] Kuvan voi liittää esikatseluun leikepöydältä. https://github.com/TIMath23/TIM/issues/179
- [ ] Kuvan kokoa esikatselussa voi säätää. Ks. https://github.com/TIMath23/TIM/issues/177
- [ ] Kuvan resoluutiota esikatselussa voi säätää.
- [ ] Kuvaa voi kiertää painikkeella esikatselussa. Ks. https://github.com/TIMath23/TIM/issues/178
- [ ] Kuvan voi poistaa esikatselusta. Ks. https://github.com/TIMath23/TIM/issues/176
- [ ] MathQuill:in lisäksi kaavaeditori hyödyntää CortexJS-kirjastoa.
