### ISSUE TITLE
4.9. TODO

### ISSUE THREAD

**Issue by dezhidki** [TIM-JYU/TIM#398]
In GitLab by @Smibu on Sep 3, 2015, 19:10

## Ens viikon hommat

* [x] Teacher viewin pisteet toimimaan muillakin kun MMCQ-pluginilla, vaihda MIN tilalle MAX
* [ ] CSV:stä muoto: username; Demokerran tunnus; Pisteet;
* [ ] CSV esim: vesal; D1; 3
* [ ] Hakemistosivuille ng-cloak
* [ ] Selattava ryhmännimi käyttäjälistaan
* [x] Valid sarake Answer tauluun
* [ ] Miten saa niin, että tietyn pvm jälkeen ryhmälaiset saavat katsoa techer-modessa toisten vastauksia (mutta eivät muokata)
* [x] https://trello.com/c/zCexyNaL
* [ ] https://trello.com/c/07MTSshc

*Juuso Valkeejärvi*
