### ISSUE TITLE
Sähköpostinotifikaatioiden checklist

### ISSUE THREAD

**Issue by dezhidki** [TIM-JYU/TIM#406]
In GitLab by @Smibu on Mar 3, 2016, 22:38

Ilmoitus dokumentin omistajalle, kun dokumenttia muutetaan tai siihen lisätään kommentteja.

## Checklist

* [x] Tavallisenkin kansalaisen mahdollisuus tilata ilmoituksia

### Ilmoitustyypit

* [x] Viesti dokujen muokkauksista/viesteista valitussa hakemistossa
* [ ] Viesti uusista dokuista valittuun hakemistoon
* [ ] Ilmoitukset velpeistä
  * [x] Uusi velp tekstiin
  * [ ] Uusi velp tehtävään
  * [x] Velppiin jätetty kommentti
  * [x] Velp poistettu
* [ ] Ilmoitukset vastauksista
  * [x] Uusi vastaus dokumenttiin
  * [ ] Uusi vastaus tiettyyn tehtävään
* [ ] Ilmoitukset uusista TIM-viesteistä tai niiden vastauksista

### Parannuksia ilmoituksiin

* [ ] Monipuolisempi käyttöliittymä
  * Mahdollista valita suuremmalla tarkkuudella, mistä tapahtumista ilmoituksia saa (esim. vain kommenttien poisto)
  * Mahdollista valita yhteystieto, johon ilmoitus lähetetään
* [ ] Oletusarvot sp-viesteille (jos haluaa tiedon uusien dokujenkin muutoksista), periytyykö tämä hakemiston viesteistä uusin dokuihin ja niistä voi poistaa jos ei halua niistä viestejä
* [ ] Pitäisikö nimi paljastaa kaikille, kun omistaja/managoija muokkaa?
* [ ] Jos lisää useita vastauksia, linkit niputetaan fiksummin yhteen (ehkä linkki vain uusimpaan vastaukseen?)

### Bugeja tai ongelmia

* [x] Ryhmäposteissa ei näy käyttäjätunnusta koskaan
* [ ] Tarkempi viesti, kun muokkaa managessa (ts. mitä kappaleita muokattiin)
* [ ] Asetuskappaleen muokkaus erikoistapauksena
