### ISSUE TITLE
Vesan TODO

### ISSUE THREAD

**Issue by dezhidki** [TIM-JYU/TIM#611]
In GitLab by @Smibu on Aug 25, 2017, 20:20

## Tarkistuslista

* [x] settings triesText: 'Yrityksiä jäljellä:'
* [x] settings add_paragraph_text: 'Lisää mielipide'
* [x] miksi tulostukseen ei tule texprintafter
* [x] MathCheck uusin versio ja points
* [x] miksi settings osan {% ei ole käytössä koko dokussa?
* [ ] pitkä poll aika ja ajan loppuminen ei lähetä vastausta
* [ ] Error kun kysely käynnistetään.  Vain TIM??
* [ ] vaihda templatejen kursorin paikka eri merkiksi kuin $
* [ ] Miksi ImageX toimii vain kirjaantuneille?

*Vesa Lappalainen*
